# Generated by Django 2.0.4 on 2018-05-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.DecimalField(decimal_places=5, max_digits=7)),
                ('dd', models.TextField(blank=True, db_column='dD', null=True)),
                ('dl', models.TextField(blank=True, db_column='dL', null=True)),
                ('dr', models.TextField(blank=True, db_column='dR', null=True)),
                ('dep', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lon', models.TextField(blank=True, null=True)),
                ('q', models.TextField(blank=True, null=True)),
                ('s', models.DecimalField(decimal_places=1, max_digits=3)),
                ('t', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quakes',
                'managed': False,
            },
        ),
    ]
